"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 13:06:01.438457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_games',
    sa.Column('state_key', sa.String(length=191), nullable=False),
    sa.Column('value', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_key')
    )
    op.create_index(op.f('ix_live_games_expires_at'), 'live_games', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_identity', sa.String(length=64), nullable=True),
    sa.Column('rng_seed', sa.BigInteger(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('days_played', sa.Integer(), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_visitors', sa.Integer(), nullable=False),
    sa.Column('total_buyers', sa.Integer(), nullable=False),
    sa.Column('total_sold_out', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_guest_identity'), 'games', ['guest_identity'], unique=False)
    op.create_index(op.f('ix_games_public_id'), 'games', ['public_id'], unique=True)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('game_configs',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_day_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('buyers', sa.Integer(), nullable=False),
    sa.Column('sold_out', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'day', 'hour', name='uq_game_day_hours')
    )
    op.create_table('game_day_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.String(length=16), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('buyers', sa.Integer(), nullable=False),
    sa.Column('sold_out', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'day', 'person_type', name='uq_game_day_types')
    )
    op.create_table('game_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=16), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recipe_ice', sa.Integer(), nullable=False),
    sa.Column('recipe_sugar', sa.Integer(), nullable=False),
    sa.Column('recipe_lemons', sa.Integer(), nullable=False),
    sa.Column('cost_per_cup', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bought_ice', sa.Integer(), nullable=False),
    sa.Column('bought_sugar', sa.Integer(), nullable=False),
    sa.Column('bought_lemons', sa.Integer(), nullable=False),
    sa.Column('bought_cups', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('buyers', sa.Integer(), nullable=False),
    sa.Column('sold_out', sa.Integer(), nullable=False),
    sa.Column('refused', sa.Integer(), nullable=False),
    sa.Column('perished_ice', sa.Integer(), nullable=False),
    sa.Column('perished_sugar', sa.Integer(), nullable=False),
    sa.Column('perished_lemons', sa.Integer(), nullable=False),
    sa.Column('perished_cups', sa.Integer(), nullable=False),
    sa.Column('perished_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_end', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refusal_reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'day', name='uq_game_days_game_day')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('days_played', sa.Integer(), nullable=False),
    sa.Column('total_cups_sold', sa.Integer(), nullable=False),
    sa.Column('total_visitors', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('best_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('best_game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['best_game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    op.drop_table('game_days')
    op.drop_table('game_day_types')
    op.drop_table('game_day_hours')
    op.drop_table('game_configs')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_index(op.f('ix_games_public_id'), table_name='games')
    op.drop_index(op.f('ix_games_guest_identity'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_live_games_expires_at'), table_name='live_games')
    op.drop_table('live_games')
    # ### end Alembic commands ###
